# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playid', models.IntegerField(unique=True)),
                ('comment', models.CharField(max_length=2048)),
            ],
        ),
    ]
